---
version: "3.9"
services:
  master:
    image: master
    ports: ["0.0.0.0:8080:8080"]
    env_file:
      - hostsports.env
  secondary-1:
    image: secondary
    ports: ["0.0.0.0:8081:8081"]
    environment:
      SECONDARY_HOST: secondary-1
      SECONDARY_PORT: 8081
  secondary-2:
    image: secondary
    ports: ["0.0.0.0:8082:8082"]
    environment:
      SECONDARY_HOST: secondary-2
      SECONDARY_PORT: 8082
  test:
    image: test
    env_file:
      - hostsports.env
