---
version: "3.9"
services:
  master:
    image: node
    ports: ["0.0.0.0:8080:8080"]
    depends_on:
      - secondary-1
      - secondary-2
    environment:
      CONFIG_PATH: master.json
  secondary-1:
    image: node
    ports: ["0.0.0.0:8081:8081"]
    environment:
      CONFIG_PATH: secondary-1.json
  secondary-2:
    image: node
    ports: ["0.0.0.0:8082:8082"]
    environment:
      CONFIG_PATH: secondary-2.json
  test:
    image: test
    depends_on:
      - master
      - secondary-1
      - secondary-2
    environment:
      CONFIG_PATH: test.json
