FROM golang:1.17.1

WORKDIR /app

COPY . .

EXPOSE 8080

ENV HOST=0.0.0.0
ENV PORT=8080

ENV SECONDARY_1_HOST=secondary-1
ENV SECONDARY_1_PORT=8081

ENV SECONDARY_2_HOST=secondary-2
ENV SECONDARY_2_PORT=8082

RUN go mod download

RUN go build -o /app/master cmd/master/main.go 

CMD [ "/app/master" ]
