---
version: "3.9"
services:
  master:
    image: master
    ports: ["0.0.0.0:8080:8080"]
  secondary-1:
    image: secondary-1
    ports: ["0.0.0.0:8081:8081"]
  secondary-2:
    image: secondary-2
    ports: ["0.0.0.0:8082:8082"]
